### ISSUE TITLE
feat: add Cancun HF variant

### ISSUE THREAD

**Issue by Nashtare** [0xPolygonZero/jerigon-test-network#1]
To test `feat/cancun` on `zk_evm` side, we need to spin up a chain following Cancun HF specs.

cf failed CI here: https://github.com/0xPolygonZero/zk_evm/actions/runs/9697609972/job/26762129241?pr=31

**Comment by atanmarko** [comment]
@cffls Could we just configure/forcefully activate Cancun fork from block 1 with current Jerigon?

**Comment by cffls** [comment]
It is possible. We can add `CancunTime: big.NewInt(0)` to dev config [here](https://github.com/0xPolygonZero/erigon/blob/9c47cce62c09ae18ed00187a211223a81a597a39/params/config.go#L121-L135).

**Comment by atanmarko** [comment]
@Nashtare @cffls I'll make a branch/image tag with the Cancun active from the block 1

We would then download `ghcr.io/0xpolygonzero/erigon:cancun` in the CI test

**Comment by atanmarko** [comment]
Fixed with https://github.com/0xPolygonZero/jerigon-test-network/tree/feat/kurtosis-network
